apiVersion: eos.netclab.dev/v1alpha1
kind: VlanInternalAllocation
metadata:
  name: dc1-spine1-1
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  order: ascending
  range:
    start: 1006
    end: 1199
---
apiVersion: eos.netclab.dev/v1alpha1
kind: StpMode
metadata:
  name: dc1-spine1-2
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  stpMode: none
---
apiVersion: eos.netclab.dev/v1alpha1
kind: IpRouting
metadata:
  name: dc1-spine1-3
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
---
apiVersion: eos.netclab.dev/v1alpha1
kind: EosCommand
metadata:
  name: dc1-spine1-4-0
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  cmds:
    ip prefix-list PL-LOOPBACKS-EVPN-OVERLAY: {}
---
apiVersion: eos.netclab.dev/v1alpha1
kind: EosCommand
metadata:
  name: dc1-spine1-4
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  cmds:
    ip prefix-list PL-LOOPBACKS-EVPN-OVERLAY:
      seq 10 permit 10.255.0.0/27 eq 32: {}
---
apiVersion: eos.netclab.dev/v1alpha1
kind: EosCommand
metadata:
  name: dc1-spine1-5-0
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  cmds:
    route-map RM-CONN-2-BGP permit 10: {}
---
apiVersion: eos.netclab.dev/v1alpha1
kind: EosCommand
metadata:
  name: dc1-spine1-5
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  cmds:
    route-map RM-CONN-2-BGP permit 10:
      match ip address prefix-list PL-LOOPBACKS-EVPN-OVERLAY: {}
---
apiVersion: eos.netclab.dev/v1alpha1
kind: EosCommand
metadata:
  name: dc1-spine1-6
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  cmds:
    router bfd:
      multihop interval 300 min-rx 300 multiplier 3: {}
---
apiVersion: eos.netclab.dev/v1alpha1
kind: EosCommand
metadata:
  name: dc1-spine1-8-0
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  cmds:
    router bgp 65100: {}
---
apiVersion: eos.netclab.dev/v1alpha1
kind: BgpGlobal
metadata:
  name: dc1-spine1-8
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  asn: 65100
  routerId: 10.255.0.1
  disableBgpDefaultIpv4Unicast: true
  maximumPaths:
    number: 4
    ecmp: 4
---
apiVersion: eos.netclab.dev/v1alpha1
kind: BgpPeerGroup
metadata:
  name: dc1-spine1-9
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  peerGroupName: EVPN-OVERLAY-PEERS
  nextHopUnchanged: true
  updateSource: Loopback0
  bfd: true
  ebgpMultihop: 3
  sendCommunityTypes:
  - EXTENDED
  - STANDARD
  maximumRoutes: 0
---
apiVersion: eos.netclab.dev/v1alpha1
kind: BgpPeerGroup
metadata:
  name: dc1-spine1-10
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  peerGroupName: IPv4-UNDERLAY-PEERS
  sendCommunityTypes:
  - EXTENDED
  - STANDARD
  maximumRoutes: 12000
---
apiVersion: eos.netclab.dev/v1alpha1
kind: BgpNeighbor
metadata:
  name: dc1-spine1-11
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  asn: 65100
  neighborIp: 10.255.0.3
  neighborAsn: 65101
  peerGroup: EVPN-OVERLAY-PEERS
  crossplane:
    compositionRef:
      name: bgpneighbors.eapi.eos.netclab.dev
---
apiVersion: eos.netclab.dev/v1alpha1
kind: EosCommand
metadata:
  name: dc1-spine1-12
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  cmds:
    router bgp 65100:
      redistribute connected route-map RM-CONN-2-BGP: {}
---
apiVersion: eos.netclab.dev/v1alpha1
kind: EosCommand
metadata:
  name: dc1-spine1-13
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  cmds:
    router bgp 65100:
      address-family evpn:
        neighbor EVPN-OVERLAY-PEERS activate: {}
---
apiVersion: eos.netclab.dev/v1alpha1
kind: EosCommand
metadata:
  name: dc1-spine1-14
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  cmds:
    router bgp 65100:
      address-family ipv4:
        no neighbor EVPN-OVERLAY-PEERS activate: {}
        neighbor IPv4-UNDERLAY-PEERS activate: {}
---
apiVersion: eos.netclab.dev/v1alpha1
kind: LoopbackInterface
metadata:
  name: dc1-spine1-15
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  ifName: Loopback0
---
apiVersion: eos.netclab.dev/v1alpha1
kind: RoutedInterface
metadata:
  name: dc1-spine1-16
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  ifName: Loopback0
  ipv4Address: 10.255.0.1
  ipv4PrefixLength: 32
