apiVersion: eos.netclab.dev/v1alpha1
kind: VlanInternalAllocation
metadata:
  name: dc1-spine1-1
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  order: ascending
  range:
    start: 1006
    end: 1199
---
apiVersion: eos.netclab.dev/v1alpha1
kind: StpMode
metadata:
  name: dc1-spine1-2
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  stpMode: none
---
apiVersion: eos.netclab.dev/v1alpha1
kind: IpRouting
metadata:
  name: dc1-spine1-3
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
---
apiVersion: eos.netclab.dev/v1alpha1
kind: BfdMultihopGlobal
metadata:
  name: dc1-spine1-6
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  interval: 300
  minRx: 300
  multiplier: 3
  crossplane:
    compositionRef:
      name: bfdmultihopglobals.eapi.eos.netclab.dev
---
apiVersion: eos.netclab.dev/v1alpha1
kind: RoutedInterface
metadata:
  name: dc1-spine1-17
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  ifName: Ethernet1
  ipv4Address: 10.255.255.0
  ipv4PrefixLength: 31
---
apiVersion: eos.netclab.dev/v1alpha1
kind: LoopbackInterface
metadata:
  name: dc1-spine1-15
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  ifName: Loopback0
---
apiVersion: eos.netclab.dev/v1alpha1
kind: RoutedInterface
metadata:
  name: dc1-spine1-16
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  ifName: Loopback0
  ipv4Address: 10.255.0.1
  ipv4PrefixLength: 32
---
apiVersion: eos.netclab.dev/v1alpha1
kind: BgpGlobal
metadata:
  name: dc1-spine1-8
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  asn: 65100
  routerId: 10.255.0.1
  disableBgpDefaultIpv4Unicast: true
  maximumPaths:
    number: 4
    ecmp: 4
---
apiVersion: eos.netclab.dev/v1alpha1
kind: BgpInterfaceExport
metadata:
  name: dc1-spine1-4
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  asn: 65100
  ifName: Loopback0
  ipv4Address: 10.255.0.1
  ipv4PrefixLength: 32
---
apiVersion: eos.netclab.dev/v1alpha1
kind: BgpPeerGroup
metadata:
  name: dc1-spine1-9
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  peerGroupName: EVPN-OVERLAY-PEERS
  nextHopUnchanged: true
  updateSource: Loopback0
  bfd: true
  ebgpMultihop: 3
  sendCommunityTypes:
  - EXTENDED
  - STANDARD
  maximumRoutes: 0
---
apiVersion: eos.netclab.dev/v1alpha1
kind: BgpPeerGroup
metadata:
  name: dc1-spine1-10
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  peerGroupName: IPv4-UNDERLAY-PEERS
  sendCommunityTypes:
  - EXTENDED
  - STANDARD
  maximumRoutes: 12000
---
apiVersion: eos.netclab.dev/v1alpha1
kind: BgpNeighbor
metadata:
  name: dc1-spine1-11
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  asn: 65100
  neighborIp: 10.255.0.3
  neighborAsn: 65101
  peerGroup: EVPN-OVERLAY-PEERS
  crossplane:
    compositionRef:
      name: bgpneighbors.eapi.eos.netclab.dev
---
apiVersion: eos.netclab.dev/v1alpha1
kind: BgpAddressFamily
metadata:
  name: dc1-spine1-13
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  asn: 65100
  addressFamily:
    afName: evpn
    neighbors:
    - pgNameOrAddress: EVPN-OVERLAY-PEERS
      active: true
  crossplane:
    compositionRef:
      name: bgpaddressfamilys.eapi.eos.netclab.dev
---
apiVersion: eos.netclab.dev/v1alpha1
kind: BgpAddressFamily
metadata:
  name: dc1-spine1-14
spec:
  endpoint: dc1-spine1.default.svc.cluster.local
  asn: 65100
  addressFamily:
    afName: ipv4
    neighbors:
    - pgNameOrAddress: EVPN-OVERLAY-PEERS
      active: false
    - pgNameOrAddress: IPv4-UNDERLAY-PEERS
      active: true
  crossplane:
    compositionRef:
      name: bgpaddressfamilys.eapi.eos.netclab.dev
